default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: bookstoremobiledev

test:
  <<: *default
  database: bookstoremobiletest

production:
  url: <%= ENV['DATABASE_URL'] %>
  <<: *default