default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: postgres
  password: Davidrama

development:
  <<: *default
  database: db/development/bookstore

test:
  <<: *default
  database: db/test/bookstore

production:
  <<: *default
  database: db/productiot/bookstore
