default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: "postgres"
  password: "Davidrama1#"

development:
  <<: *default
  database: bookstoremobiledev

test:
  <<: *default
  database: bookstoremobiletest

production:
  <<: *default
  database: bookstoremobilepro