# SQLite. Versions 3.8.0 and up are supported.

default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
